panda_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
    - panda_finger_joint2
  constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.05
          joint1: {trajectory: 0.1, goal: 0.1}
          joint2: {trajectory: 0.1, goal: 0.1}
          joint3: {trajectory: 0.1, goal: 0.1}
          joint4: {trajectory: 0.1, goal: 0.1}
          joint5: {trajectory: 0.1, goal: 0.1}
          joint6: {trajectory: 0.1, goal: 0.1}
          joint7: {trajectory: 0.1, goal: 0.1}
          joint8: {trajectory: 0.1, goal: 0.1}
          joint9: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  